### PR TITLE
Dynamic Declaration Added

### PR DESCRIPTION
**Pull request by Leoperon**

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Thanks @Leoperon ❤️

**Comment by Ananthavijay** [comment]
@Leoperon Infinitehello.cpp should me moved to GCC folder and not Turbo c++

**Comment by Leoperon** [comment]
ok sure

**Comment by Ananthavijay** [comment]
Thanks

**Comment by Leoperon** [comment]
U r welcome. Happy to work with you

**Comment by Ananthavijay** [comment]
@Leoperon if u want to work with me message to this mail vj35.cool@gmail.com

**Pull request merged**
