### PR TITLE
Add License file

### PR DESCRIPTION
**Pull request by mathagician**
Add License file

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Thanks a lot @mathagician ❤️ 
The license file is wrong 😞 
The file name should be LICENSE and you will have to choose one out of many options..choose mit

**Comment by Ananthavijay** [comment]
Check this link : https://help.github.com/en/articles/adding-a-license-to-a-repository
dont have the name of the file as License.md

**Comment by mathagician** [comment]
> Thanks a lot @mathagician ❤️
> The license file is wrong 😞
> The file name should be LICENSE and you will have to choose one out of many options..choose mit

I have done the changes

**Comment by Ananthavijay** [comment]
Thanks @mathagician for your efforts 💜❤

**Pull request merged**
