### PR TITLE
Added a programme for Binary search

### PR DESCRIPTION
**Pull request by aayushgarg-03**

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@aayushgarg-03 this is already done. sorry

**Comment by aayushgarg-03** [comment]
Can you please suggest a topic which is not taken and would be Important to
consider

**Comment by Ananthavijay** [comment]
IDK just add some things that u did when u were a beginner

**Comment by aayushgarg-03** [comment]
I have done Binary Search Tree using Inorder and Preorder Traversal
Please check it

**Pull request closed without merging**
