### PR TITLE
Add GNU GENERAL PUBLIC LICENSE

### PR DESCRIPTION
**Pull request by kamontat**

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Sorry @kamontat  This is already assigned to someone else..If he does not complete within today then I will merge yours 😢 😞

**Comment by kamontat** [comment]
Ok :)

**Comment by kamontat** [comment]
Otherwise, you can close this if it deprecates.

**Comment by Ananthavijay** [comment]
Let me close this 😢

**Pull request closed without merging**
