### PR TITLE
Shell sort

### PR DESCRIPTION
**Pull request by Leoperon**
Basic sorting Algorithm

### CODE REVIEW

**Comment by Leoperon** [comment]
Any suggestions?

**Comment by Ananthavijay** [comment]
Please rebase and Commit @Leoperon

**Comment by Ananthavijay** [comment]
Good @Leoperon Just reabase and commit

**Comment by Leoperon** [comment]
I'm not able to add my name to the contribution section

**Comment by Ananthavijay** [comment]
Ok I think you didn't understand what I said.
Just delete your fork, make a new fork then make a commit and make a Pull request

**Comment by Leoperon** [comment]
ok

**Pull request closed without merging**
