### PR TITLE
gcc

### PR DESCRIPTION
**Pull request by developer22-university**
c++ two short programs

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Fibonacci series has already been done
So @developer22-university Pls remove the file and make a commit again

**Comment by developer22-university** [comment]
PLEASE MERGE GCD FUNCTION CODE

**Comment by Ananthavijay** [comment]
@developer22-university Please add your name to contributor's section in readme

**Comment by developer22-university** [comment]
how to merge readme i added but faced problems

**Comment by Ananthavijay** [comment]
Thanks @developer22-university ❤️

**Pull request merged**
