### PR TITLE
Roll no verification

### PR DESCRIPTION
**Pull request by Leoperon**
Using IF-ELSE in C++

### CODE REVIEW

**Comment by Leoperon** [comment]
Any suggestion?

**Comment by Leoperon** [comment]
Because just now I have received an mail assuming my pr to be spam. Can anyone help me?

**Comment by Ananthavijay** [comment]
IDK 🤔

**Comment by Ananthavijay** [comment]
Anyway add your name to contributor's section in readme

**Comment by Leoperon** [comment]
I'm not able to add my name to the contributer section

**Comment by kanha1998** [comment]
what is the condition of a valid roll number should be mentioned for eg number of max digits ,letter if any present

**Comment by Leoperon** [comment]
Condition: Only positive integers are allowed

**Comment by kanha1998** [comment]
Its not true always you took ur own assumption

**Comment by Ananthavijay** [comment]
I think this is an useless program.
Sorry @Leoperon

**Pull request closed without merging**
