### PR TITLE
Linear Search

### PR DESCRIPTION
**Pull request by vedant3620**

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@vedant3620 Please add your name to contributor's section in readme

**Comment by vedant3620** [comment]
> @vedant3620 Please add your name to contributor's section in readme

it's already added

**Comment by Ananthavijay** [comment]
Where @vedant3620

**Comment by vedant3620** [comment]
> Where @vedant3620

it was in other pull request I have closed that one

**Comment by Ananthavijay** [comment]
Thanks @vedant3620

**Pull request merged**
